export default [
  'And that was the end of everything. But it was also a beginning.',
  'I don\'t even have time to explain why I don\'t have time to explain.',
  'Evil so dark it despises other evil.',
  'I was not forged in light. But I believe where our paths cross, ground... could break.',
  'My path\'s my own.',
  'Ah, yes. The Awoken. Out there, wavering between the Light and the Dark. A side should always be taken, little light. Even if it\'s the wrong side.',
  'It\'s a day for pretty speeches and medals. But we know the real fight takes place out there.',
  'All ends are beginnings.',
  'Another one of these hardened military systems... And a few centuries of entropy working against me.',
  'Welcome to the last safe City on Earth -- the only place the Traveler can still protect. It took centuries to build. Now... we\'re counting every day it stands.',
  'Why is the right place always so terrifying?',
  'Access key? I don\'t need an access key. DOS is more complicated.',
  'Every Ghost is born knowing that we have to find our Guardian. We don\'t know what they look like. Not on the outside, anyway. On the inside, I\'d always known who you were. And that together, we could be something more. When you think think about everything we\'ve seen, everything we\'ve done, I feel like... I made the right choice. ... Thanks - you know - for being my Guardian',
  'You know it\'s starting to concern me how seldom you talk. We\'ve been through a lot together, the neural symbiosis is pretty far progressed, but you\'d be surprised how little I understand what you\'re thinking.',
  'All Titans interested in Commander Zavala’s crochet course should speak with a Frame for details.',
  'Hello, this is Cayde-6 of the Vanguard. I realize this is an abuse of the Tower P.A., but whoever took my sparrow, I will find you. And you\'ll wear a sign that says you stole... Nevermind, nevermind! It\'s right here.',
  'Often, when we guess at others\' motives, we reveal only our own.',
  'There are many tales, told throughout the City to frighten children. Lately those tales have stopped. Now... the children are frightened anyway.',
  'For centuries we feared the forces of Darkness massing against us. We sought to hide and cower beneath a broken god. No more. These Guardians show us what we are, what we have always been and what we will be again. We are what remains of the Light and we will not be stamped out.',
  'Taniks has no House. He kneels before no banner, owes allegiance to no Kell. He is a murderer, and very good at what he does. I have been tracking him since Wolves broke their chains, yes? Now Taniks works for Wolf pack, but not for long...',
  'One little, two little, three little Hive. You killed so many, now none are alive.',
  'When you whisper to the void, does it whisper back?',
  'Message for Shaxx. Message for Shaxx. Oh dear... he hits.',
  'Package for Xûr. What\'s Xûr?',
  'Package for Warlock. Stop floating. Bad package.',
  'Inappropriate picture message received from Cayde.',
  'Bad address. That Tower\'s empty. Isn\'t it?'
]